In [45]:
import pandas as pd

In [46]:
a=[32,4,36,7,43]

In [47]:
sr=pd.Series(a)

In [48]:
print(sr)

0    32
1     4
2    36
3     7
4    43
dtype: int64

**DataFrame**

In [49]:
weather={
    "temp":[32,45,30,40,31],
    "humidity":[80,60,78,21,23],
    "windspeed":[6,7,2,7,4],
    "event":["rain","sunny","snow","snow","rain"]
}

In [50]:
df=pd.DataFrame(weather)
df

   temp  humidity  windspeed  event
0    32        80          6   rain
1    45        60          7  sunny
2    30        78          2   snow
3    40        21          7   snow
4    31        23          4   rain

In [51]:
df.head(2)

   temp  humidity  windspeed  event
0    32        80          6   rain
1    45        60          7  sunny

In [52]:
df.tail(2)

   temp  humidity  windspeed event
3    40        21          7  snow
4    31        23          4  rain

In [53]:
df[["humidity","windspeed"]]

   humidity  windspeed
0        80          6
1        60          7
2        78          2
3        21          7
4        23          4

#loc & iloc

In [54]:
df.loc[0:2,["humidity","windspeed"]]

   humidity  windspeed
0        80          6
1        60          7
2        78          2

In [55]:
df.iloc[:4,2:]

   windspeed  event
0          6   rain
1          7  sunny
2          2   snow
3          7   snow

In [56]:
df.iloc[:,-1].unique()

array(['rain', 'sunny', 'snow'], dtype=object)

In [57]:
df[df["temp"]>30]

   temp  humidity  windspeed  event
0    32        80          6   rain
1    45        60          7  sunny
3    40        21          7   snow
4    31        23          4   rain

In [58]:
import numpy as np

weather={
    "temp":[32,45,30,40,31,90],
    "humidity":[80,60,78,21,23,np.nan],
    "windspeed":[6,7,2,7,4,np.nan],
    "event":["rain","sunny","snow","snow","rain",np.nan]
}

In [59]:
df1 = pd.DataFrame(weather)
print(df1)

   temp  humidity  windspeed  event
0    32      80.0        6.0   rain
1    45      60.0        7.0  sunny
2    30      78.0        2.0   snow
3    40      21.0        7.0   snow
4    31      23.0        4.0   rain
5    90       NaN        NaN    NaN

In [60]:
df1.isnull()

    temp  humidity  windspeed  event
0  False     False      False  False
1  False     False      False  False
2  False     False      False  False
3  False     False      False  False
4  False     False      False  False
5  False      True       True   True

In [61]:
df1.isnull().sum()

temp         0
humidity     1
windspeed    1
event        1
dtype: int64

* fillna(0/mean/median)
* dropna()   {dropna(axis=0/1}
* inplace(actual DataFrame)

In [62]:
df1.fillna(0)

   temp  humidity  windspeed  event
0    32      80.0        6.0   rain
1    45      60.0        7.0  sunny
2    30      78.0        2.0   snow
3    40      21.0        7.0   snow
4    31      23.0        4.0   rain
5    90       0.0        0.0      0

In [63]:
df1.dropna(axis=1)

   temp
0    32
1    45
2    30
3    40
4    31
5    90

In [64]:
df.dropna() #axis=>1

   temp  humidity  windspeed  event
0    32        80          6   rain
1    45        60          7  sunny
2    30        78          2   snow
3    40        21          7   snow
4    31        23          4   rain

In [65]:
df1

   temp  humidity  windspeed  event
0    32      80.0        6.0   rain
1    45      60.0        7.0  sunny
2    30      78.0        2.0   snow
3    40      21.0        7.0   snow
4    31      23.0        4.0   rain
5    90       NaN        NaN    NaN

In [66]:
df1.dropna(axis=0,inplace=True)

In [67]:
df1["event"]=df1["event"].map({"sunny":0, "rain":1, "snow":2})
df1

   temp  humidity  windspeed  event
0    32      80.0        6.0      1
1    45      60.0        7.0      0
2    30      78.0        2.0      2
3    40      21.0        7.0      2
4    31      23.0        4.0      1