In [2]:
Ppl=['b','b','g','b','g']
Ppl.sort()
print(Ppl)

['b', 'b', 'b', 'g', 'g']

In [3]:
import numpy as np
import pandas as pd

In [14]:
a=[10,20,30]
b= np.array(a) + 10
print(b)
print(np.sum(b))
print(np.mean(b))
print(np.min(a))
print(np.max(a))

[20 30 40]
90
30.0
10
30

In [26]:
data = {
     'Name': ['Nav','Guri','Armaan','Shurli'],
     'Marks':[69,65,72,45]
}
df = pd.DataFrame(data)
print(df)

     Name  Marks
0     Nav     69
1    Guri     65
2  Armaan     72
3  Shurli     45

In [27]:
name = ['Nav','Guri','Armaan','Shurli']
marks = [69,65,72,45]
df = pd.DataFrame({'Name': name, 'Marks': marks})
print(df)

     Name  Marks
0     Nav     69
1    Guri     65
2  Armaan     72
3  Shurli     45

In [28]:
df.head()

     Name  Marks
0     Nav     69
1    Guri     65
2  Armaan     72
3  Shurli     45

In [29]:
df.tail()

     Name  Marks
0     Nav     69
1    Guri     65
2  Armaan     72
3  Shurli     45

In [31]:
print(df['Name'])

0       Nav
1      Guri
2    Armaan
3    Shurli
Name: Name, dtype: object

In [33]:
display(df['Name'])

0       Nav
1      Guri
2    Armaan
3    Shurli
Name: Name, dtype: object

In [38]:
print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].min())

62.75
72
45

In [39]:
print(df['Marks']>70)

0    False
1    False
2     True
3    False
Name: Marks, dtype: bool

In [44]:
print(df[df['Marks']>60])

     Name  Marks
0     Nav     69
1    Guri     65
2  Armaan     72